@startuml
participant UI
participant Server
participant Database
participant "Email Service" as EM

title Registration Flow

group Email Validation
UI -> UI: get email
UI -> Server: Create User and validate email
Server -> EM: Send verficiation email
Server -> Database: Save user and email verification code with expiry.
UI -> UI: Get Validation code from user and username
end group

UI -> Server: confirm Validation code and generateRegistrationOptions

group Registration
group Get Options
Server -> Database: Get User
Database --> Server
Server -> Database: Get User credentials (if present)
Database --> Server
Server -> Server: generateRegistrationOptions
Server -> Database: Save User Challenge
Server --> UI: return registration options
end Options
UI -> UI: StartRegistration
group Verify
UI -> Server: Verify Registration 
Server -> Database: Get User
Database --> Server
Server -> Database: Get User Challenge (?)
Database --> Server
Server -> Server: verifyRegistrationResponse
Server -> Database: Save credential for user
Server  --> UI: return verfied result


end Registration



hide footbox

@enduml